#! /usr/bin/env perl

# === Perl keyword recognizer for the intuit_more regex heuristic ===
#
# Perl's S_intuit_more (toke.c) decides whether a `[` or `{` following a
# variable inside a pattern begins a subscript or a regex character-class /
# quantifier.  One branch of its weighting machine calls keyword(): if a run
# of consecutive alphas inside `[...]` spells a Perl keyword, that strongly
# implies it is NOT a character class (weight -= 150).
#
# Perl recognizes keywords with a generated trie (keywords.c, built by
# regen/keywords.pl via Devel::Tokenizer::C).  That file is GPL/Artistic and
# can't be copied into this MIT project.  The *names* of the keywords, however,
# are uncopyrightable facts, so we list them below and regenerate our own
# equivalent trie.  The list is the set of names keyword() can return, i.e.
# every KEY_* in perl's keywords.h (excluding the KEY_NULL "not a keyword"
# sentinel).
#
# To refresh against a newer perl:
#   grep -oE '^#define KEY_[A-Za-z0-9_]+' /path/to/perl5/keywords.h \
#     | sed 's/^#define KEY_//' | grep -vx NULL
# then paste the result into the __DATA__ section and re-run this script.

use v5.38;
use Path::Tiny qw/path/;

my @keywords =
  grep { length } map { chomp; s/^\s+|\s+$//gr } grep { /\S/ && !/^#/ } <DATA>;

# Group by length; within a length we emit a character-trie.
my %by_len;
push @{ $by_len{ length $_ } }, $_ for @keywords;

my @out;
push @out, <<'HEAD';
/* THIS FILE IS GENERATED BY generate_intuit_keywords.pl
 *
 * Recognizes Perl keywords for the intuit_more() regex heuristic.  See that
 * generator for why we regenerate this rather than reuse perl's keywords.c.
 *
 * tsp_is_perl_keyword(s, len) returns true iff s[0..len) is exactly a Perl
 * keyword.  It does no allocation and never reads past s[len-1].
 */

#ifndef TSP_INTUIT_KEYWORDS_H
#define TSP_INTUIT_KEYWORDS_H

#include <stdbool.h>

static bool tsp_is_perl_keyword(const char *s, int len) {
  switch (len) {
HEAD

sub char_literal {
  my ($c) = @_;
  # All keyword chars are [A-Za-z0-9_]; safe as plain C char literals.
  return "'$c'";
}

# Recursively emit a trie node for the set of @$words, all of length $len and
# sharing the first $depth characters.  $ind is the current indentation.
sub emit_node {
  my ($words, $depth, $len, $ind) = @_;

  if ($depth == $len) {
    push @out, "${ind}return true;\n";
    return;
  }

  # A single remaining word collapses to a flat char comparison instead of a
  # tower of one-case switches (keeps long unique keywords readable).
  if (@$words == 1) {
    my $w = $words->[0];
    my @cmp = map { "s[$_] == " . char_literal(substr($w, $_, 1)) } ($depth .. $len - 1);
    push @out, "${ind}return " . join(" && ", @cmp) . ";\n";
    return;
  }

  my %by_char;
  push @{ $by_char{ substr($_, $depth, 1) } }, $_ for @$words;

  push @out, "${ind}switch (s[$depth]) {\n";
  for my $ch (sort keys %by_char) {
    push @out, "${ind}  case ${\ char_literal($ch)}:\n";
    emit_node($by_char{$ch}, $depth + 1, $len, "${ind}    ");
  }
  push @out, "${ind}}\n";
  push @out, "${ind}return false;\n";
}

for my $len (sort { $a <=> $b } keys %by_len) {
  push @out, "    case $len:\n";
  emit_node($by_len{$len}, 0, $len, "      ");
}

push @out, <<'TAIL';
  }
  return false;
}

#endif /* TSP_INTUIT_KEYWORDS_H */
TAIL

path('./src/tsp_intuit_keywords.h')->spew(join '', @out);

say "Generated src/tsp_intuit_keywords.h with ${\ scalar @keywords} keywords";

__DATA__
ADJUST
AUTOLOAD
BEGIN
CHECK
DESTROY
END
INIT
UNITCHECK
__CLASS__
__DATA__
__END__
__FILE__
__LINE__
__PACKAGE__
__SUB__
abs
accept
alarm
and
atan2
bind
binmode
bless
caller
catch
chdir
chmod
chomp
chop
chown
chr
chroot
class
close
closedir
cmp
connect
continue
cos
crypt
dbmclose
dbmopen
defer
defined
delete
die
do
dump
each
else
elsif
endgrent
endhostent
endnetent
endprotoent
endpwent
endservent
eof
eq
eval
evalbytes
exec
exists
exit
exp
fc
fcntl
field
fileno
finally
flock
for
foreach
fork
format
formline
ge
getc
getgrent
getgrgid
getgrnam
gethostbyaddr
gethostbyname
gethostent
getlogin
getnetbyaddr
getnetbyname
getnetent
getpeername
getpgrp
getppid
getpriority
getprotobyname
getprotobynumber
getprotoent
getpwent
getpwnam
getpwuid
getservbyname
getservbyport
getservent
getsockname
getsockopt
glob
gmtime
goto
grep
gt
hex
if
index
int
ioctl
isa
join
keys
kill
last
lc
lcfirst
le
length
link
listen
local
localtime
lock
log
lstat
lt
m
map
method
mkdir
msgctl
msgget
msgrcv
msgsnd
my
ne
next
no
not
oct
open
opendir
or
ord
our
pack
package
pipe
pop
pos
print
printf
prototype
push
q
qq
qr
quotemeta
qw
qx
rand
read
readdir
readline
readlink
readpipe
recv
redo
ref
rename
require
reset
return
reverse
rewinddir
rindex
rmdir
s
say
scalar
seek
seekdir
select
semctl
semget
semop
send
setgrent
sethostent
setnetent
setpgrp
setpriority
setprotoent
setpwent
setservent
setsockopt
shift
shmctl
shmget
shmread
shmwrite
shutdown
sin
sleep
socket
socketpair
sort
splice
split
sprintf
sqrt
srand
stat
state
study
sub
substr
symlink
syscall
sysopen
sysread
sysseek
system
syswrite
tell
telldir
tie
tied
time
times
tr
try
truncate
uc
ucfirst
umask
undef
unless
unlink
unpack
unshift
untie
until
use
utime
values
vec
wait
waitpid
wantarray
warn
while
write
x
xor
y
