#! /usr/bin/env perl

use v5.38;
use Path::Tiny qw/path/;

# === Statement keywords for recovery peek ===

# Always a statement keyword
my @always = qw(package use no class role);

# Only a declaration if followed by an identifier name
# (e.g., `sub foo` is a declaration, bare `sub` is anonymous)
my @needs_name = qw(sub method);

my @all = sort(@always, @needs_name);

# Derive the unique first chars
my @first_chars = sort keys %{{ map { substr($_, 0, 1) => 1 } @all }};

# Derive the character set used across all keywords (for the word-reading loop)
my @word_chars = sort keys %{{ map { $_ => 1 } map { split //, $_ } @all }};

# Build the C expressions
my $first_char_test = join(' || ', map { "la == '$_'" } @first_chars);
my $word_char_test  = join(' || ', map { "la == '$_'" } @word_chars);

my $always_test = join(" || ", map { qq{strcmp(word, "$_") == 0} } @always);
my $named_test  = join(" || ", map { qq{strcmp(word, "$_") == 0} } @needs_name);

path('./src/tsp_keywords.h')->spew(<<C);
/* THIS FILE IS GENERATED BY generate_keywords.pl
 *
 * Statement keywords recognized by peek_is_statement_keyword().
 * To add a keyword, edit the \@keywords list in generate_keywords.pl
 * and re-run: perl generate_keywords.pl
 *
 * Current keywords: @{[ join ', ', @all ]}
 */

// First-char filter: returns PEEK_NO_MATCH immediately if the
// lookahead can't start any statement keyword.
#define KEYWORD_FIRST_CHAR_FILTER(la) \\
  (!($first_char_test))

// Word-reading loop: characters that appear in any keyword.
#define KEYWORD_WORD_CHAR(la) \\
  ($word_char_test)

// Keyword classification: sets `kind` to one of the KwKind values.
//   KW_NONE       — not a statement keyword (a plain bareword / autoquote key)
//   KW_ALWAYS     — always a statement keyword (package, use, no, class, role)
//   KW_NEEDS_NAME — only a declaration if followed by a name (sub, method)
// Unlike a bare match this never returns: the caller decides what to do with a
// non-keyword, which may still be a fat-comma autoquote key.
#define KEYWORD_MATCH(word, kind) do { \\
    if ($always_test) { \\
      (kind) = KW_ALWAYS; \\
    } else if ($named_test) { \\
      (kind) = KW_NEEDS_NAME; \\
    } else { \\
      (kind) = KW_NONE; \\
    } \\
  } while(0)
C

say "Generated src/tsp_keywords.h with @{[ scalar @all ]} keywords";
say "  first chars: @first_chars";
say "  word chars:  @word_chars";
say "  always:      @{[ join ', ', @always ]}";
say "  needs_name:  @{[ join ', ', @needs_name ]}";
