// NOTE - this is generated by unicode_ranges.pl
module.exports = {
  // these patterns are simply XID_Start followed by XID_Continue, minus things which don't match perl's \p{Word}
  identifier: /[[_\p{XID_Start}]--[\u{b7}\u{387}\u{1369}-\u{1370}\u{19da}\u{2118}\u{212e}]][[\p{XID_Continue}]--[\u{b7}\u{387}\u{1369}-\u{1370}\u{19da}\u{2118}\u{212e}]]*/v,
  // this adds in any amount of :: before or in between identifiers
  bareword:   /((::)|([[_\p{XID_Start}]--[\u{b7}\u{387}\u{1369}-\u{1370}\u{19da}\u{2118}\u{212e}]][[\p{XID_Continue}]--[\u{b7}\u{387}\u{1369}-\u{1370}\u{19da}\u{2118}\u{212e}]]*))+/v,
}
