/* THIS FILE IS GENERATED BY generate_intuit_keywords.pl
 *
 * Recognizes Perl keywords for the intuit_more() regex heuristic.  See that
 * generator for why we regenerate this rather than reuse perl's keywords.c.
 *
 * tsp_is_perl_keyword(s, len) returns true iff s[0..len) is exactly a Perl
 * keyword.  It does no allocation and never reads past s[len-1].
 */

#ifndef TSP_INTUIT_KEYWORDS_H
#define TSP_INTUIT_KEYWORDS_H

#include <stdbool.h>

static bool tsp_is_perl_keyword(const char *s, int len) {
  switch (len) {
    case 1:
      switch (s[0]) {
        case 'm':
          return true;
        case 'q':
          return true;
        case 's':
          return true;
        case 'x':
          return true;
        case 'y':
          return true;
      }
      return false;
    case 2:
      switch (s[0]) {
        case 'd':
          return s[1] == 'o';
        case 'e':
          return s[1] == 'q';
        case 'f':
          return s[1] == 'c';
        case 'g':
          switch (s[1]) {
            case 'e':
              return true;
            case 't':
              return true;
          }
          return false;
        case 'i':
          return s[1] == 'f';
        case 'l':
          switch (s[1]) {
            case 'c':
              return true;
            case 'e':
              return true;
            case 't':
              return true;
          }
          return false;
        case 'm':
          return s[1] == 'y';
        case 'n':
          switch (s[1]) {
            case 'e':
              return true;
            case 'o':
              return true;
          }
          return false;
        case 'o':
          return s[1] == 'r';
        case 'q':
          switch (s[1]) {
            case 'q':
              return true;
            case 'r':
              return true;
            case 'w':
              return true;
            case 'x':
              return true;
          }
          return false;
        case 't':
          return s[1] == 'r';
        case 'u':
          return s[1] == 'c';
      }
      return false;
    case 3:
      switch (s[0]) {
        case 'E':
          return s[1] == 'N' && s[2] == 'D';
        case 'a':
          switch (s[1]) {
            case 'b':
              return s[2] == 's';
            case 'n':
              return s[2] == 'd';
          }
          return false;
        case 'c':
          switch (s[1]) {
            case 'h':
              return s[2] == 'r';
            case 'm':
              return s[2] == 'p';
            case 'o':
              return s[2] == 's';
          }
          return false;
        case 'd':
          return s[1] == 'i' && s[2] == 'e';
        case 'e':
          switch (s[1]) {
            case 'o':
              return s[2] == 'f';
            case 'x':
              return s[2] == 'p';
          }
          return false;
        case 'f':
          return s[1] == 'o' && s[2] == 'r';
        case 'h':
          return s[1] == 'e' && s[2] == 'x';
        case 'i':
          switch (s[1]) {
            case 'n':
              return s[2] == 't';
            case 's':
              return s[2] == 'a';
          }
          return false;
        case 'l':
          return s[1] == 'o' && s[2] == 'g';
        case 'm':
          return s[1] == 'a' && s[2] == 'p';
        case 'n':
          return s[1] == 'o' && s[2] == 't';
        case 'o':
          switch (s[1]) {
            case 'c':
              return s[2] == 't';
            case 'r':
              return s[2] == 'd';
            case 'u':
              return s[2] == 'r';
          }
          return false;
        case 'p':
          switch (s[1]) {
            case 'o':
              switch (s[2]) {
                case 'p':
                  return true;
                case 's':
                  return true;
              }
              return false;
          }
          return false;
        case 'r':
          return s[1] == 'e' && s[2] == 'f';
        case 's':
          switch (s[1]) {
            case 'a':
              return s[2] == 'y';
            case 'i':
              return s[2] == 'n';
            case 'u':
              return s[2] == 'b';
          }
          return false;
        case 't':
          switch (s[1]) {
            case 'i':
              return s[2] == 'e';
            case 'r':
              return s[2] == 'y';
          }
          return false;
        case 'u':
          return s[1] == 's' && s[2] == 'e';
        case 'v':
          return s[1] == 'e' && s[2] == 'c';
        case 'x':
          return s[1] == 'o' && s[2] == 'r';
      }
      return false;
    case 4:
      switch (s[0]) {
        case 'I':
          return s[1] == 'N' && s[2] == 'I' && s[3] == 'T';
        case 'b':
          return s[1] == 'i' && s[2] == 'n' && s[3] == 'd';
        case 'c':
          return s[1] == 'h' && s[2] == 'o' && s[3] == 'p';
        case 'd':
          return s[1] == 'u' && s[2] == 'm' && s[3] == 'p';
        case 'e':
          switch (s[1]) {
            case 'a':
              return s[2] == 'c' && s[3] == 'h';
            case 'l':
              return s[2] == 's' && s[3] == 'e';
            case 'v':
              return s[2] == 'a' && s[3] == 'l';
            case 'x':
              switch (s[2]) {
                case 'e':
                  return s[3] == 'c';
                case 'i':
                  return s[3] == 't';
              }
              return false;
          }
          return false;
        case 'f':
          return s[1] == 'o' && s[2] == 'r' && s[3] == 'k';
        case 'g':
          switch (s[1]) {
            case 'e':
              return s[2] == 't' && s[3] == 'c';
            case 'l':
              return s[2] == 'o' && s[3] == 'b';
            case 'o':
              return s[2] == 't' && s[3] == 'o';
            case 'r':
              return s[2] == 'e' && s[3] == 'p';
          }
          return false;
        case 'j':
          return s[1] == 'o' && s[2] == 'i' && s[3] == 'n';
        case 'k':
          switch (s[1]) {
            case 'e':
              return s[2] == 'y' && s[3] == 's';
            case 'i':
              return s[2] == 'l' && s[3] == 'l';
          }
          return false;
        case 'l':
          switch (s[1]) {
            case 'a':
              return s[2] == 's' && s[3] == 't';
            case 'i':
              return s[2] == 'n' && s[3] == 'k';
            case 'o':
              return s[2] == 'c' && s[3] == 'k';
          }
          return false;
        case 'n':
          return s[1] == 'e' && s[2] == 'x' && s[3] == 't';
        case 'o':
          return s[1] == 'p' && s[2] == 'e' && s[3] == 'n';
        case 'p':
          switch (s[1]) {
            case 'a':
              return s[2] == 'c' && s[3] == 'k';
            case 'i':
              return s[2] == 'p' && s[3] == 'e';
            case 'u':
              return s[2] == 's' && s[3] == 'h';
          }
          return false;
        case 'r':
          switch (s[1]) {
            case 'a':
              return s[2] == 'n' && s[3] == 'd';
            case 'e':
              switch (s[2]) {
                case 'a':
                  return s[3] == 'd';
                case 'c':
                  return s[3] == 'v';
                case 'd':
                  return s[3] == 'o';
              }
              return false;
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 'e':
                  return s[3] == 'k';
                case 'n':
                  return s[3] == 'd';
              }
              return false;
            case 'o':
              return s[2] == 'r' && s[3] == 't';
            case 'q':
              return s[2] == 'r' && s[3] == 't';
            case 't':
              return s[2] == 'a' && s[3] == 't';
          }
          return false;
        case 't':
          switch (s[1]) {
            case 'e':
              return s[2] == 'l' && s[3] == 'l';
            case 'i':
              switch (s[2]) {
                case 'e':
                  return s[3] == 'd';
                case 'm':
                  return s[3] == 'e';
              }
              return false;
          }
          return false;
        case 'w':
          switch (s[1]) {
            case 'a':
              switch (s[2]) {
                case 'i':
                  return s[3] == 't';
                case 'r':
                  return s[3] == 'n';
              }
              return false;
          }
          return false;
      }
      return false;
    case 5:
      switch (s[0]) {
        case 'B':
          return s[1] == 'E' && s[2] == 'G' && s[3] == 'I' && s[4] == 'N';
        case 'C':
          return s[1] == 'H' && s[2] == 'E' && s[3] == 'C' && s[4] == 'K';
        case 'a':
          switch (s[1]) {
            case 'l':
              return s[2] == 'a' && s[3] == 'r' && s[4] == 'm';
            case 't':
              return s[2] == 'a' && s[3] == 'n' && s[4] == '2';
          }
          return false;
        case 'b':
          return s[1] == 'l' && s[2] == 'e' && s[3] == 's' && s[4] == 's';
        case 'c':
          switch (s[1]) {
            case 'a':
              return s[2] == 't' && s[3] == 'c' && s[4] == 'h';
            case 'h':
              switch (s[2]) {
                case 'd':
                  return s[3] == 'i' && s[4] == 'r';
                case 'm':
                  return s[3] == 'o' && s[4] == 'd';
                case 'o':
                  switch (s[3]) {
                    case 'm':
                      return s[4] == 'p';
                    case 'w':
                      return s[4] == 'n';
                  }
                  return false;
              }
              return false;
            case 'l':
              switch (s[2]) {
                case 'a':
                  return s[3] == 's' && s[4] == 's';
                case 'o':
                  return s[3] == 's' && s[4] == 'e';
              }
              return false;
            case 'r':
              return s[2] == 'y' && s[3] == 'p' && s[4] == 't';
          }
          return false;
        case 'd':
          return s[1] == 'e' && s[2] == 'f' && s[3] == 'e' && s[4] == 'r';
        case 'e':
          return s[1] == 'l' && s[2] == 's' && s[3] == 'i' && s[4] == 'f';
        case 'f':
          switch (s[1]) {
            case 'c':
              return s[2] == 'n' && s[3] == 't' && s[4] == 'l';
            case 'i':
              return s[2] == 'e' && s[3] == 'l' && s[4] == 'd';
            case 'l':
              return s[2] == 'o' && s[3] == 'c' && s[4] == 'k';
          }
          return false;
        case 'i':
          switch (s[1]) {
            case 'n':
              return s[2] == 'd' && s[3] == 'e' && s[4] == 'x';
            case 'o':
              return s[2] == 'c' && s[3] == 't' && s[4] == 'l';
          }
          return false;
        case 'l':
          switch (s[1]) {
            case 'o':
              return s[2] == 'c' && s[3] == 'a' && s[4] == 'l';
            case 's':
              return s[2] == 't' && s[3] == 'a' && s[4] == 't';
          }
          return false;
        case 'm':
          return s[1] == 'k' && s[2] == 'd' && s[3] == 'i' && s[4] == 'r';
        case 'p':
          return s[1] == 'r' && s[2] == 'i' && s[3] == 'n' && s[4] == 't';
        case 'r':
          switch (s[1]) {
            case 'e':
              return s[2] == 's' && s[3] == 'e' && s[4] == 't';
            case 'm':
              return s[2] == 'd' && s[3] == 'i' && s[4] == 'r';
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              return s[2] == 'm' && s[3] == 'o' && s[4] == 'p';
            case 'h':
              return s[2] == 'i' && s[3] == 'f' && s[4] == 't';
            case 'l':
              return s[2] == 'e' && s[3] == 'e' && s[4] == 'p';
            case 'p':
              return s[2] == 'l' && s[3] == 'i' && s[4] == 't';
            case 'r':
              return s[2] == 'a' && s[3] == 'n' && s[4] == 'd';
            case 't':
              switch (s[2]) {
                case 'a':
                  return s[3] == 't' && s[4] == 'e';
                case 'u':
                  return s[3] == 'd' && s[4] == 'y';
              }
              return false;
          }
          return false;
        case 't':
          return s[1] == 'i' && s[2] == 'm' && s[3] == 'e' && s[4] == 's';
        case 'u':
          switch (s[1]) {
            case 'm':
              return s[2] == 'a' && s[3] == 's' && s[4] == 'k';
            case 'n':
              switch (s[2]) {
                case 'd':
                  return s[3] == 'e' && s[4] == 'f';
                case 't':
                  switch (s[3]) {
                    case 'i':
                      switch (s[4]) {
                        case 'e':
                          return true;
                        case 'l':
                          return true;
                      }
                      return false;
                  }
                  return false;
              }
              return false;
            case 't':
              return s[2] == 'i' && s[3] == 'm' && s[4] == 'e';
          }
          return false;
        case 'w':
          switch (s[1]) {
            case 'h':
              return s[2] == 'i' && s[3] == 'l' && s[4] == 'e';
            case 'r':
              return s[2] == 'i' && s[3] == 't' && s[4] == 'e';
          }
          return false;
      }
      return false;
    case 6:
      switch (s[0]) {
        case 'A':
          return s[1] == 'D' && s[2] == 'J' && s[3] == 'U' && s[4] == 'S' && s[5] == 'T';
        case 'a':
          return s[1] == 'c' && s[2] == 'c' && s[3] == 'e' && s[4] == 'p' && s[5] == 't';
        case 'c':
          switch (s[1]) {
            case 'a':
              return s[2] == 'l' && s[3] == 'l' && s[4] == 'e' && s[5] == 'r';
            case 'h':
              return s[2] == 'r' && s[3] == 'o' && s[4] == 'o' && s[5] == 't';
          }
          return false;
        case 'd':
          return s[1] == 'e' && s[2] == 'l' && s[3] == 'e' && s[4] == 't' && s[5] == 'e';
        case 'e':
          return s[1] == 'x' && s[2] == 'i' && s[3] == 's' && s[4] == 't' && s[5] == 's';
        case 'f':
          switch (s[1]) {
            case 'i':
              return s[2] == 'l' && s[3] == 'e' && s[4] == 'n' && s[5] == 'o';
            case 'o':
              return s[2] == 'r' && s[3] == 'm' && s[4] == 'a' && s[5] == 't';
          }
          return false;
        case 'g':
          return s[1] == 'm' && s[2] == 't' && s[3] == 'i' && s[4] == 'm' && s[5] == 'e';
        case 'l':
          switch (s[1]) {
            case 'e':
              return s[2] == 'n' && s[3] == 'g' && s[4] == 't' && s[5] == 'h';
            case 'i':
              return s[2] == 's' && s[3] == 't' && s[4] == 'e' && s[5] == 'n';
          }
          return false;
        case 'm':
          switch (s[1]) {
            case 'e':
              return s[2] == 't' && s[3] == 'h' && s[4] == 'o' && s[5] == 'd';
            case 's':
              switch (s[2]) {
                case 'g':
                  switch (s[3]) {
                    case 'c':
                      return s[4] == 't' && s[5] == 'l';
                    case 'g':
                      return s[4] == 'e' && s[5] == 't';
                    case 'r':
                      return s[4] == 'c' && s[5] == 'v';
                    case 's':
                      return s[4] == 'n' && s[5] == 'd';
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 'p':
          return s[1] == 'r' && s[2] == 'i' && s[3] == 'n' && s[4] == 't' && s[5] == 'f';
        case 'r':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 'n':
                  return s[3] == 'a' && s[4] == 'm' && s[5] == 'e';
                case 't':
                  return s[3] == 'u' && s[4] == 'r' && s[5] == 'n';
              }
              return false;
            case 'i':
              return s[2] == 'n' && s[3] == 'd' && s[4] == 'e' && s[5] == 'x';
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'c':
              return s[2] == 'a' && s[3] == 'l' && s[4] == 'a' && s[5] == 'r';
            case 'e':
              switch (s[2]) {
                case 'l':
                  return s[3] == 'e' && s[4] == 'c' && s[5] == 't';
                case 'm':
                  switch (s[3]) {
                    case 'c':
                      return s[4] == 't' && s[5] == 'l';
                    case 'g':
                      return s[4] == 'e' && s[5] == 't';
                  }
                  return false;
              }
              return false;
            case 'h':
              switch (s[2]) {
                case 'm':
                  switch (s[3]) {
                    case 'c':
                      return s[4] == 't' && s[5] == 'l';
                    case 'g':
                      return s[4] == 'e' && s[5] == 't';
                  }
                  return false;
              }
              return false;
            case 'o':
              return s[2] == 'c' && s[3] == 'k' && s[4] == 'e' && s[5] == 't';
            case 'p':
              return s[2] == 'l' && s[3] == 'i' && s[4] == 'c' && s[5] == 'e';
            case 'u':
              return s[2] == 'b' && s[3] == 's' && s[4] == 't' && s[5] == 'r';
            case 'y':
              return s[2] == 's' && s[3] == 't' && s[4] == 'e' && s[5] == 'm';
          }
          return false;
        case 'u':
          switch (s[1]) {
            case 'n':
              switch (s[2]) {
                case 'l':
                  switch (s[3]) {
                    case 'e':
                      return s[4] == 's' && s[5] == 's';
                    case 'i':
                      return s[4] == 'n' && s[5] == 'k';
                  }
                  return false;
                case 'p':
                  return s[3] == 'a' && s[4] == 'c' && s[5] == 'k';
              }
              return false;
          }
          return false;
        case 'v':
          return s[1] == 'a' && s[2] == 'l' && s[3] == 'u' && s[4] == 'e' && s[5] == 's';
      }
      return false;
    case 7:
      switch (s[0]) {
        case 'D':
          return s[1] == 'E' && s[2] == 'S' && s[3] == 'T' && s[4] == 'R' && s[5] == 'O' && s[6] == 'Y';
        case '_':
          switch (s[1]) {
            case '_':
              switch (s[2]) {
                case 'E':
                  return s[3] == 'N' && s[4] == 'D' && s[5] == '_' && s[6] == '_';
                case 'S':
                  return s[3] == 'U' && s[4] == 'B' && s[5] == '_' && s[6] == '_';
              }
              return false;
          }
          return false;
        case 'b':
          return s[1] == 'i' && s[2] == 'n' && s[3] == 'm' && s[4] == 'o' && s[5] == 'd' && s[6] == 'e';
        case 'c':
          return s[1] == 'o' && s[2] == 'n' && s[3] == 'n' && s[4] == 'e' && s[5] == 'c' && s[6] == 't';
        case 'd':
          switch (s[1]) {
            case 'b':
              return s[2] == 'm' && s[3] == 'o' && s[4] == 'p' && s[5] == 'e' && s[6] == 'n';
            case 'e':
              return s[2] == 'f' && s[3] == 'i' && s[4] == 'n' && s[5] == 'e' && s[6] == 'd';
          }
          return false;
        case 'f':
          switch (s[1]) {
            case 'i':
              return s[2] == 'n' && s[3] == 'a' && s[4] == 'l' && s[5] == 'l' && s[6] == 'y';
            case 'o':
              return s[2] == 'r' && s[3] == 'e' && s[4] == 'a' && s[5] == 'c' && s[6] == 'h';
          }
          return false;
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'p':
                      switch (s[4]) {
                        case 'g':
                          return s[5] == 'r' && s[6] == 'p';
                        case 'p':
                          return s[5] == 'i' && s[6] == 'd';
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 'l':
          return s[1] == 'c' && s[2] == 'f' && s[3] == 'i' && s[4] == 'r' && s[5] == 's' && s[6] == 't';
        case 'o':
          return s[1] == 'p' && s[2] == 'e' && s[3] == 'n' && s[4] == 'd' && s[5] == 'i' && s[6] == 'r';
        case 'p':
          return s[1] == 'a' && s[2] == 'c' && s[3] == 'k' && s[4] == 'a' && s[5] == 'g' && s[6] == 'e';
        case 'r':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 'a':
                  return s[3] == 'd' && s[4] == 'd' && s[5] == 'i' && s[6] == 'r';
                case 'q':
                  return s[3] == 'u' && s[4] == 'i' && s[5] == 'r' && s[6] == 'e';
                case 'v':
                  return s[3] == 'e' && s[4] == 'r' && s[5] == 's' && s[6] == 'e';
              }
              return false;
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 'e':
                  return s[3] == 'k' && s[4] == 'd' && s[5] == 'i' && s[6] == 'r';
                case 't':
                  return s[3] == 'p' && s[4] == 'g' && s[5] == 'r' && s[6] == 'p';
              }
              return false;
            case 'h':
              return s[2] == 'm' && s[3] == 'r' && s[4] == 'e' && s[5] == 'a' && s[6] == 'd';
            case 'p':
              return s[2] == 'r' && s[3] == 'i' && s[4] == 'n' && s[5] == 't' && s[6] == 'f';
            case 'y':
              switch (s[2]) {
                case 'm':
                  return s[3] == 'l' && s[4] == 'i' && s[5] == 'n' && s[6] == 'k';
                case 's':
                  switch (s[3]) {
                    case 'c':
                      return s[4] == 'a' && s[5] == 'l' && s[6] == 'l';
                    case 'o':
                      return s[4] == 'p' && s[5] == 'e' && s[6] == 'n';
                    case 'r':
                      return s[4] == 'e' && s[5] == 'a' && s[6] == 'd';
                    case 's':
                      return s[4] == 'e' && s[5] == 'e' && s[6] == 'k';
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 't':
          return s[1] == 'e' && s[2] == 'l' && s[3] == 'l' && s[4] == 'd' && s[5] == 'i' && s[6] == 'r';
        case 'u':
          switch (s[1]) {
            case 'c':
              return s[2] == 'f' && s[3] == 'i' && s[4] == 'r' && s[5] == 's' && s[6] == 't';
            case 'n':
              return s[2] == 's' && s[3] == 'h' && s[4] == 'i' && s[5] == 'f' && s[6] == 't';
          }
          return false;
        case 'w':
          return s[1] == 'a' && s[2] == 'i' && s[3] == 't' && s[4] == 'p' && s[5] == 'i' && s[6] == 'd';
      }
      return false;
    case 8:
      switch (s[0]) {
        case 'A':
          return s[1] == 'U' && s[2] == 'T' && s[3] == 'O' && s[4] == 'L' && s[5] == 'O' && s[6] == 'A' && s[7] == 'D';
        case '_':
          switch (s[1]) {
            case '_':
              switch (s[2]) {
                case 'D':
                  return s[3] == 'A' && s[4] == 'T' && s[5] == 'A' && s[6] == '_' && s[7] == '_';
                case 'F':
                  return s[3] == 'I' && s[4] == 'L' && s[5] == 'E' && s[6] == '_' && s[7] == '_';
                case 'L':
                  return s[3] == 'I' && s[4] == 'N' && s[5] == 'E' && s[6] == '_' && s[7] == '_';
              }
              return false;
          }
          return false;
        case 'c':
          switch (s[1]) {
            case 'l':
              return s[2] == 'o' && s[3] == 's' && s[4] == 'e' && s[5] == 'd' && s[6] == 'i' && s[7] == 'r';
            case 'o':
              return s[2] == 'n' && s[3] == 't' && s[4] == 'i' && s[5] == 'n' && s[6] == 'u' && s[7] == 'e';
          }
          return false;
        case 'd':
          return s[1] == 'b' && s[2] == 'm' && s[3] == 'c' && s[4] == 'l' && s[5] == 'o' && s[6] == 's' && s[7] == 'e';
        case 'e':
          switch (s[1]) {
            case 'n':
              switch (s[2]) {
                case 'd':
                  switch (s[3]) {
                    case 'g':
                      return s[4] == 'r' && s[5] == 'e' && s[6] == 'n' && s[7] == 't';
                    case 'p':
                      return s[4] == 'w' && s[5] == 'e' && s[6] == 'n' && s[7] == 't';
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 'f':
          return s[1] == 'o' && s[2] == 'r' && s[3] == 'm' && s[4] == 'l' && s[5] == 'i' && s[6] == 'n' && s[7] == 'e';
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'g':
                      switch (s[4]) {
                        case 'r':
                          switch (s[5]) {
                            case 'e':
                              return s[6] == 'n' && s[7] == 't';
                            case 'g':
                              return s[6] == 'i' && s[7] == 'd';
                            case 'n':
                              return s[6] == 'a' && s[7] == 'm';
                          }
                          return false;
                      }
                      return false;
                    case 'l':
                      return s[4] == 'o' && s[5] == 'g' && s[6] == 'i' && s[7] == 'n';
                    case 'p':
                      switch (s[4]) {
                        case 'w':
                          switch (s[5]) {
                            case 'e':
                              return s[6] == 'n' && s[7] == 't';
                            case 'n':
                              return s[6] == 'a' && s[7] == 'm';
                            case 'u':
                              return s[6] == 'i' && s[7] == 'd';
                          }
                          return false;
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 'r':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 'a':
                  switch (s[3]) {
                    case 'd':
                      switch (s[4]) {
                        case 'l':
                          switch (s[5]) {
                            case 'i':
                              switch (s[6]) {
                                case 'n':
                                  switch (s[7]) {
                                    case 'e':
                                      return true;
                                    case 'k':
                                      return true;
                                  }
                                  return false;
                              }
                              return false;
                          }
                          return false;
                        case 'p':
                          return s[5] == 'i' && s[6] == 'p' && s[7] == 'e';
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'g':
                      return s[4] == 'r' && s[5] == 'e' && s[6] == 'n' && s[7] == 't';
                    case 'p':
                      return s[4] == 'w' && s[5] == 'e' && s[6] == 'n' && s[7] == 't';
                  }
                  return false;
              }
              return false;
            case 'h':
              switch (s[2]) {
                case 'm':
                  return s[3] == 'w' && s[4] == 'r' && s[5] == 'i' && s[6] == 't' && s[7] == 'e';
                case 'u':
                  return s[3] == 't' && s[4] == 'd' && s[5] == 'o' && s[6] == 'w' && s[7] == 'n';
              }
              return false;
            case 'y':
              return s[2] == 's' && s[3] == 'w' && s[4] == 'r' && s[5] == 'i' && s[6] == 't' && s[7] == 'e';
          }
          return false;
        case 't':
          return s[1] == 'r' && s[2] == 'u' && s[3] == 'n' && s[4] == 'c' && s[5] == 'a' && s[6] == 't' && s[7] == 'e';
      }
      return false;
    case 9:
      switch (s[0]) {
        case 'U':
          return s[1] == 'N' && s[2] == 'I' && s[3] == 'T' && s[4] == 'C' && s[5] == 'H' && s[6] == 'E' && s[7] == 'C' && s[8] == 'K';
        case '_':
          return s[1] == '_' && s[2] == 'C' && s[3] == 'L' && s[4] == 'A' && s[5] == 'S' && s[6] == 'S' && s[7] == '_' && s[8] == '_';
        case 'e':
          switch (s[1]) {
            case 'n':
              return s[2] == 'd' && s[3] == 'n' && s[4] == 'e' && s[5] == 't' && s[6] == 'e' && s[7] == 'n' && s[8] == 't';
            case 'v':
              return s[2] == 'a' && s[3] == 'l' && s[4] == 'b' && s[5] == 'y' && s[6] == 't' && s[7] == 'e' && s[8] == 's';
          }
          return false;
        case 'g':
          return s[1] == 'e' && s[2] == 't' && s[3] == 'n' && s[4] == 'e' && s[5] == 't' && s[6] == 'e' && s[7] == 'n' && s[8] == 't';
        case 'l':
          return s[1] == 'o' && s[2] == 'c' && s[3] == 'a' && s[4] == 'l' && s[5] == 't' && s[6] == 'i' && s[7] == 'm' && s[8] == 'e';
        case 'p':
          return s[1] == 'r' && s[2] == 'o' && s[3] == 't' && s[4] == 'o' && s[5] == 't' && s[6] == 'y' && s[7] == 'p' && s[8] == 'e';
        case 'q':
          return s[1] == 'u' && s[2] == 'o' && s[3] == 't' && s[4] == 'e' && s[5] == 'm' && s[6] == 'e' && s[7] == 't' && s[8] == 'a';
        case 'r':
          return s[1] == 'e' && s[2] == 'w' && s[3] == 'i' && s[4] == 'n' && s[5] == 'd' && s[6] == 'd' && s[7] == 'i' && s[8] == 'r';
        case 's':
          return s[1] == 'e' && s[2] == 't' && s[3] == 'n' && s[4] == 'e' && s[5] == 't' && s[6] == 'e' && s[7] == 'n' && s[8] == 't';
        case 'w':
          return s[1] == 'a' && s[2] == 'n' && s[3] == 't' && s[4] == 'a' && s[5] == 'r' && s[6] == 'r' && s[7] == 'a' && s[8] == 'y';
      }
      return false;
    case 10:
      switch (s[0]) {
        case 'e':
          switch (s[1]) {
            case 'n':
              switch (s[2]) {
                case 'd':
                  switch (s[3]) {
                    case 'h':
                      return s[4] == 'o' && s[5] == 's' && s[6] == 't' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                    case 's':
                      return s[4] == 'e' && s[5] == 'r' && s[6] == 'v' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'h':
                      return s[4] == 'o' && s[5] == 's' && s[6] == 't' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                    case 's':
                      switch (s[4]) {
                        case 'e':
                          return s[5] == 'r' && s[6] == 'v' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                        case 'o':
                          return s[5] == 'c' && s[6] == 'k' && s[7] == 'o' && s[8] == 'p' && s[9] == 't';
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'h':
                      return s[4] == 'o' && s[5] == 's' && s[6] == 't' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                    case 's':
                      switch (s[4]) {
                        case 'e':
                          return s[5] == 'r' && s[6] == 'v' && s[7] == 'e' && s[8] == 'n' && s[9] == 't';
                        case 'o':
                          return s[5] == 'c' && s[6] == 'k' && s[7] == 'o' && s[8] == 'p' && s[9] == 't';
                      }
                      return false;
                  }
                  return false;
              }
              return false;
            case 'o':
              return s[2] == 'c' && s[3] == 'k' && s[4] == 'e' && s[5] == 't' && s[6] == 'p' && s[7] == 'a' && s[8] == 'i' && s[9] == 'r';
          }
          return false;
      }
      return false;
    case 11:
      switch (s[0]) {
        case '_':
          return s[1] == '_' && s[2] == 'P' && s[3] == 'A' && s[4] == 'C' && s[5] == 'K' && s[6] == 'A' && s[7] == 'G' && s[8] == 'E' && s[9] == '_' && s[10] == '_';
        case 'e':
          return s[1] == 'n' && s[2] == 'd' && s[3] == 'p' && s[4] == 'r' && s[5] == 'o' && s[6] == 't' && s[7] == 'o' && s[8] == 'e' && s[9] == 'n' && s[10] == 't';
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'p':
                      switch (s[4]) {
                        case 'e':
                          return s[5] == 'e' && s[6] == 'r' && s[7] == 'n' && s[8] == 'a' && s[9] == 'm' && s[10] == 'e';
                        case 'r':
                          switch (s[5]) {
                            case 'i':
                              return s[6] == 'o' && s[7] == 'r' && s[8] == 'i' && s[9] == 't' && s[10] == 'y';
                            case 'o':
                              return s[6] == 't' && s[7] == 'o' && s[8] == 'e' && s[9] == 'n' && s[10] == 't';
                          }
                          return false;
                      }
                      return false;
                    case 's':
                      return s[4] == 'o' && s[5] == 'c' && s[6] == 'k' && s[7] == 'n' && s[8] == 'a' && s[9] == 'm' && s[10] == 'e';
                  }
                  return false;
              }
              return false;
          }
          return false;
        case 's':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'p':
                      switch (s[4]) {
                        case 'r':
                          switch (s[5]) {
                            case 'i':
                              return s[6] == 'o' && s[7] == 'r' && s[8] == 'i' && s[9] == 't' && s[10] == 'y';
                            case 'o':
                              return s[6] == 't' && s[7] == 'o' && s[8] == 'e' && s[9] == 'n' && s[10] == 't';
                          }
                          return false;
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
      }
      return false;
    case 12:
      switch (s[0]) {
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'n':
                      switch (s[4]) {
                        case 'e':
                          switch (s[5]) {
                            case 't':
                              switch (s[6]) {
                                case 'b':
                                  switch (s[7]) {
                                    case 'y':
                                      switch (s[8]) {
                                        case 'a':
                                          return s[9] == 'd' && s[10] == 'd' && s[11] == 'r';
                                        case 'n':
                                          return s[9] == 'a' && s[10] == 'm' && s[11] == 'e';
                                      }
                                      return false;
                                  }
                                  return false;
                              }
                              return false;
                          }
                          return false;
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
      }
      return false;
    case 13:
      switch (s[0]) {
        case 'g':
          switch (s[1]) {
            case 'e':
              switch (s[2]) {
                case 't':
                  switch (s[3]) {
                    case 'h':
                      switch (s[4]) {
                        case 'o':
                          switch (s[5]) {
                            case 's':
                              switch (s[6]) {
                                case 't':
                                  switch (s[7]) {
                                    case 'b':
                                      switch (s[8]) {
                                        case 'y':
                                          switch (s[9]) {
                                            case 'a':
                                              return s[10] == 'd' && s[11] == 'd' && s[12] == 'r';
                                            case 'n':
                                              return s[10] == 'a' && s[11] == 'm' && s[12] == 'e';
                                          }
                                          return false;
                                      }
                                      return false;
                                  }
                                  return false;
                              }
                              return false;
                          }
                          return false;
                      }
                      return false;
                    case 's':
                      switch (s[4]) {
                        case 'e':
                          switch (s[5]) {
                            case 'r':
                              switch (s[6]) {
                                case 'v':
                                  switch (s[7]) {
                                    case 'b':
                                      switch (s[8]) {
                                        case 'y':
                                          switch (s[9]) {
                                            case 'n':
                                              return s[10] == 'a' && s[11] == 'm' && s[12] == 'e';
                                            case 'p':
                                              return s[10] == 'o' && s[11] == 'r' && s[12] == 't';
                                          }
                                          return false;
                                      }
                                      return false;
                                  }
                                  return false;
                              }
                              return false;
                          }
                          return false;
                      }
                      return false;
                  }
                  return false;
              }
              return false;
          }
          return false;
      }
      return false;
    case 14:
      return s[0] == 'g' && s[1] == 'e' && s[2] == 't' && s[3] == 'p' && s[4] == 'r' && s[5] == 'o' && s[6] == 't' && s[7] == 'o' && s[8] == 'b' && s[9] == 'y' && s[10] == 'n' && s[11] == 'a' && s[12] == 'm' && s[13] == 'e';
    case 16:
      return s[0] == 'g' && s[1] == 'e' && s[2] == 't' && s[3] == 'p' && s[4] == 'r' && s[5] == 'o' && s[6] == 't' && s[7] == 'o' && s[8] == 'b' && s[9] == 'y' && s[10] == 'n' && s[11] == 'u' && s[12] == 'm' && s[13] == 'b' && s[14] == 'e' && s[15] == 'r';
  }
  return false;
}

#endif /* TSP_INTUIT_KEYWORDS_H */
