name: Release Flow
on:
  push:
    branches:
      - master

concurrency:
  group: release-master
  cancel-in-progress: true

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - run: tree-sitter generate
      - run: tree-sitter test
      - run: ./copy-to-release
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release
          publish_branch: release
          user_name: GH Actions [beep-boop]
          user_email: release-flow@beep.boop
